[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dice_game = "3PQj16kni7CemUJ3kymxuCWqwgtvHALhguFTrEKs3JrK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
